# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        # needs: env # need env file to run test
        env:
            IMAGE: koi-api
            NODE_ENV: development
            DATABASE_HOST: localhost
            DATABASE_PORT: 27017
            DATABASE_DBNAME: stores-api
            PORT: 3000
        strategy:
            matrix:
                node-version: [18.3.0]
        # pg db
        services:
            mongo:
                image: mongo:5.0-focal
                env:
                    MONGO_INITDB_DATABASE: stores-api
                    MONGO_INITDB_ROOT_USERNAME: ""
                    MONGO_INITDB_ROOT_PASSWORD: ""
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd mongo
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: npm install
              run: npm ci
            - name: start api and integration testing
              run: npm run test
              env:
                  CI: true
